### ISSUE TITLE
Error on upload

### ISSUE THREAD

**Issue by bukhariamir** [gwen001/BBstats#2]
when I try to upload the sample certificate, it gives me this error, am I doing it wrong or something to do with blackboard version.

![image](https://user-images.githubusercontent.com/44634073/74219695-9b3a2e00-4cbe-11ea-8b98-4625f21d3f64.png)

**Comment by gwen001** [comment]
Don't know what you're talking about, it doesn't look like my program since there is nothing to upload.

**Comment by bukhariamir** [comment]
Sorry, pasted at the wrong place.
